version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: fastapi-db
    ports:
      - "5433:5432"
    networks:
      - mynetwork

  web:
    build:
      context: .
    environment:
      - ENVIRONMENT=docker
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
